In [1]:
from datasets import load_dataset
data=load_dataset("BramVanroy/conll2003")

# Extract the list of string labels to map integers back to text
# Standard CoNLL-2003 tags: ['O', 'B-PER', 'I-PER', 'B-ORG', 'I-ORG', 'B-LOC', 'I-LOC', 'B-MISC', 'I-MISC']
dataUK=data['train'].to_pandas().drop(columns=['pos_tags', 'chunk_tags', 'id'])
dataUK

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

,tokens,ner_tags
0,"[EU, rejects, German, call, to, boycott, Briti...","[3, 0, 7, 0, 0, 0, 7, 0, 0]"
1,"[Peter, Blackburn]","[1, 2]"
2,"[BRUSSELS, 1996-08-22]","[5, 0]"
3,"[The, European, Commission, said, on, Thursday...","[0, 3, 4, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, ..."
4,"[Germany, 's, representative, to, the, Europea...","[5, 0, 0, 0, 0, 3, 4, 0, 0, 0, 1, 2, 0, 0, 0, ..."
...,...,...
14036,"[on, Friday, :]","[0, 0, 0]"
14037,"[Division, two]","[0, 0]"
14038,"[Plymouth, 2, Preston, 1]","[3, 0, 3, 0]"
14039,"[Division, three]","[0, 0]"
14040,"[Swansea, 1, Lincoln, 2]","[3, 0, 3, 0]"

In [ ]:
"""One file only"""
import os
import glob
import pandas as pd

def load_custom_tsv(file_path):
    sentences=[]
    ner_tags=[]

    current_sentence=[]
    current_tags=[]

    with open(file_path, 'r', encoding='utf-8') as f:
        try:            # Skip the first two lines (the link and the empty line)
            next(f)
            next(f)
        except StopIteration:
            pass # Failsafe just in case the file is completely empty

        for line in f:
            line=line.strip()

            if not line:    #empty line aka end of sentence
                if current_sentence:
                    sentences.append(list(current_sentence))
                    ner_tags.append(list(current_tags))
                    current_sentence.clear()
                    current_tags.clear()
                continue
            parts=line.split('\t')

            if len(parts) >= 2:
                token=parts[0]
                tag=parts[-1]

                current_sentence.append(token)
                current_tags.append(tag)

        if current_sentence:
            sentences.append(list(current_sentence))
            ner_tags.append(list(current_tags))

    df = pd.DataFrame({'tokens': sentences, 'ner_tags': ner_tags})
    
    return df

file_path = r"C:\Users\anna-\OneDrive\Desktop\ITU\4th semester\NLP and Deep Learning\af_afrol_1.txt.tsv"
dataGlobal = load_custom_tsv(file_path)
dataGlobal

,tokens,ner_tags
0,"[afrol, News, ,, 27, January, -, David, Kato, ...","[B-Organization, I-Organization, O, B-Date, I-..."
1,"[Shocked, Ugandan, gay, activists, promise, to...","[O, B-NORP, O, O, O, O, O, O, O, O, O, O, O, O..."
2,"[Mr, Kato, earned, international, fame, when, ...","[O, B-Person, O, O, O, O, O, O, O, O, O, O, O,..."
3,"[The, front, page, represented, the, strongest...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
4,"[Until, now, .]","[O, O, O]"
5,"[Today, ,, Mr, Kato, indeed, was, found, dead,...","[O, O, O, B-Person, O, O, O, O, O, O, O, O]"
6,"[Preliminary, reports, from, Kampala, indicate...","[O, O, O, B-Location, O, O, O, O, O, O, O, O, ..."
7,"[The, activist, ,, it, seems, ,, had, to, pay,...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
8,"[Mr, Kato, had, achieved, some, extraordinary,...","[O, B-Person, O, O, O, O, O, O, O, O, O, O]"
9,"[Following, his, complaint, ,, Uganda, 's, Sup...","[O, O, O, O, B-Location, I-Organization, I-Org..."
10,"[The, Court, on, 3, January, ruled, that, "", t...","[O, O, O, B-Date, I-Date, O, O, O, O, O, O, O,..."
11,"[The, court, case, ,, fronted, by, Mr, Kato, a...","[O, O, O, O, O, O, O, B-Person, O, O, O, B-Org..."
12,"[The, case, and, massive, international, press...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
13,"[While, the, country, last, year, was, steerin...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
14,"[For, SMUG, ,, the, news, of, Mr, Kato, 's, ki...","[O, B-Organization, O, O, O, O, O, B-Person, O..."
15,"[The, mourning, Uganda, gay, activists, first,...","[O, O, B-Location, O, O, O, O, O, O, O, O, O, ..."
16,"[Fear, is, spreading, .]","[O, O, O, O]"
17,"[But, the, group, quickly, decided, to, keep, ...","[O, O, O, O, O, O, O, O, O, O, O]"
18,"[Speaking, about, what, the, death, of, Mr, Ka...","[O, O, O, O, O, O, O, B-Person, O, O, O, O, O,..."
19,"[The, death, of, David, will, only, be, honour...","[O, O, O, B-Person, O, O, O, O, O, O, O, O, O,..."
20,"[David, is, gone, and, many, of, us, will, fol...","[B-Person, O, O, O, O, O, O, O, O, O, O, O, O,..."
21,"[The, sexual, minorities, group, today, could,...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
22,"[But, even, a, growing, number, of, Ugandan, o...","[O, O, O, O, O, O, B-NORP, O, O, O, O, O, B-Or..."
23,"[Val, Kalende, ,, leader, of, the, Board, at, ...","[B-Person, I-Person, O, O, O, O, B-Organizatio..."
24,"[The, Ugandan, government, and, the, so, -, ca...","[O, B-NORP, O, O, O, O, O, O, B-Location, B-NO..."
25,"[Mr, Mugisha, agreed, and, called, on, religio...","[O, B-Person, O, O, O, O, O, O, O, O, O, O, O,..."
26,"[The, death, of, Mr, Kato, could, mean, the, S...","[O, O, O, O, B-Person, O, O, O, B-Organization..."
27,"[There, are, now, calls, from, abroad, and, ho...","[O, O, O, O, O, O, O, O, O, O, O, O, O, B-Pers..."
28,"["", The, Ugandan, government, must, immediatel...","[O, O, B-NORP, O, O, O, O, O, O, O, O, O, O, O..."
29,"[Mr, Mugisha, added, that, government, now, ne...","[O, B-Person, O, O, O, O, O, O, O, O, O, O, O,..."

In [5]:
import os
import glob
import pandas as pd

def load_tsvs_from_folder(folder_path):
    all_sentences = []
    all_ner_tags = []
    all_regions = []

    search_pattern = os.path.join(folder_path, "*.tsv")
    file_list = glob.glob(search_pattern)
    
    for file_path in file_list:
        filename = os.path.basename(file_path)
        region_name = filename.split('_')[0]
        current_sentence = []
        current_tags = []

        with open(file_path, 'r', encoding='utf-8') as f:
            for _ in range(2):       # Skip the first two lines
                try:
                    next(f)
                except StopIteration:
                    break

            for line in f:
                line = line.strip()

                if not line:    # EMPTY LINE: Sentence is over
                    if current_sentence:
                        all_sentences.append(list(current_sentence))
                        all_ner_tags.append(list(current_tags))
                        all_regions.append(region_name)
                        current_sentence.clear()
                        current_tags.clear()
                    continue 
                    
                parts = line.split('\t')    # TEXT: Extract token and primary tag
                if len(parts) >= 2:
                    token = parts[0].strip()
                    raw_tag = parts[1].strip() # Grab the FIRST tag to avoid nested tags

                    current_sentence.append(token)
                    current_tags.append(raw_tag)

            if current_sentence:        # END OF FILE: Catch the final sentence
                all_sentences.append(list(current_sentence))
                all_ner_tags.append(list(current_tags))
                all_regions.append(region_name)

    df = pd.DataFrame({'tokens': all_sentences, 'ner_tags': all_ner_tags, 'region': all_regions,})
    return df

folder_path = r".\processed_annotated"
dataGlobal = load_tsvs_from_folder(folder_path)

dataGlobal

,tokens,ner_tags,region
0,"[DURBAN, ,, May, 20, 2022, (, IPS, ), -, Gover...","[B-Location, O, B-Date, I-Date, I-Date, O, B-O...",afs
1,"[These, were, among, the, diverse, opinions, o...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...",afs
2,"[Hundreds, of, delegates, ,, including, world,...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...",afs
3,"[Sessions, and, panel, discussions, highlighte...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...",afs
4,"[Speaking, during, the, closing, ceremony, on,...","[O, O, O, O, O, O, B-Date, O, B-Location, I-Lo...",afs
...,...,...,...
21312,"[Fanny, is, about, to, give, a, picture, of, h...","[B-Person, O, O, O, O, O, O, O, O, O, O, O, O,...",ven
21313,"[But, the, majority, of, the, civil, society, ...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...",ven
21314,"[It, ’s, all, about, a, perpetual, and, useful...","[O, O, O, O, O, O, O, O, O, O, O, O, B-Person,...",ven
21315,"[Lusverti, adds, :, “, The, struggle, of, thes...","[B-Person, O, O, O, O, O, O, O, O, O, O, O, O,...",ven
21316,"[So, ,, as, Sánchez, warns, ,, these, mothers,...","[O, O, O, B-Person, O, O, O, O, O, O, O, O, O,...",ven

In [ ]:
IDtoLabel_UK = {
    0: 'O',
    1: 'B-Person',
    2: 'I-Person',
    3: 'B-Organization',
    4: 'I-Organization',
    5: 'B-Location',
    6: 'I-Location',
    7: 'B-Misc',
    8: 'I-Misc'
}
IDtoLabel_US = {
    0:'O',
    1:'B-Misc',
    2:'B-Date',
    3:'I-Date',
    4:'B-Person',
    5:'I-Person',
    6:'B-NORP',
    7:'B-Misc',
    8:'I-Misc',
    9:'B-Misc',
    10:'I-Misc',
    11:'B-Organization',
    12:'I-Organization',
    13:'B-Misc',
    14:'I-Misc',
    15:'B-Misc',
    16:'B-Money',
    17:'I-Money',
    18:'B-Misc',
    19:'I-Misc',
    20:'B-Facility',
    21:'B-Date',
    22:'I-Misc',
    23:'B-Location',
    24:'B-Misc',
    25:'I-Misc',
    26:'I-NORP',
    27:'I-Location',
    28:'B-Product',
    29:'I-Date',
    30:'B-Misc',
    31:'I-Misc',
    32:'I-Facility',
    33:'B-Misc',
    34:'I-Product',
    35:'I-Misc',
    36:'I-Misc'
}
LabelToID = {
    'O': 0,
    'B-Date': 1,
    'I-Date': 2,
    'B-Person': 3,
    'I-Person': 4,
    'B-Location': 5,
    'I-Location': 6,
    'B-Facility': 7,
    'I-Facility': 8,
    'B-Organization': 9,
    'I-Organization': 10,
    'B-Misc': 11,
    'I-Misc': 12,
    'B-Money': 13,
    'I-Money': 14,
    'B-NORP': 15,
    'I-NORP': 16,
    'B-Product': 17,
    'I-Product': 18
}